import {
  Accessibility,
  Activity,
  AlarmClock,
  AlignCenter,
  AlignLeft,
  AlignRight,
  Anchor,
  Angry,
  Aperture,
  Apple,
  Archive,
  ArrowDown,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpLeft,
  ArrowUpRight,
  AtSign,
  Atom,
  Award,
  Baby,
  Backpack,
  BadgeCheck,
  Ban,
  Banana,
  Banknote,
  BarChart3,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  Beer,
  Bell,
  BellOff,
  BellRing,
  Bike,
  Binary,
  Bird,
  Bluetooth,
  Bold,
  Book,
  BookMarked,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Boxes,
  Braces,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building,
  Building2,
  Bus,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Camera,
  Candy,
  Car,
  Cat,
  Check,
  CheckCheck,
  ChefHat,
  Cherry,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleX,
  Clapperboard,
  Clipboard,
  ClipboardCheck,
  ClipboardCopy,
  ClipboardList,
  Clock,
  Cloud,
  CloudDownload,
  CloudLightning,
  CloudMoon,
  CloudRain,
  CloudSnow,
  CloudSun,
  CloudUpload,
  Code,
  Coffee,
  Cog,
  Coins,
  Command,
  Compass,
  Component,
  Contact,
  Cookie,
  CornerDownLeft,
  CornerDownRight,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreditCard,
  Croissant,
  Crop,
  Crown,
  CupSoda,
  Database,
  Dice5,
  Disc,
  Divide,
  Dna,
  Dog,
  DollarSign,
  Download,
  Droplet,
  Droplets,
  Egg,
  Equal,
  Eraser,
  Euro,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  FastForward,
  File,
  FileCheck,
  FileCode,
  FileImage,
  FileMinus,
  FilePlus,
  FileSearch,
  FileText,
  FileVideo,
  FileX,
  Files,
  Film,
  Filter,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Flower,
  Flower2,
  Focus,
  Folder,
  FolderMinus,
  FolderOpen,
  FolderPlus,
  Footprints,
  Frame,
  Frown,
  Fuel,
  Gamepad2,
  Gauge,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  GitMerge,
  GitPullRequest,
  Glasses,
  Globe,
  GraduationCap,
  Grid3x3,
  Hammer,
  Hand,
  Handshake,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HeartHandshake,
  History,
  Home,
  Hotel,
  Hourglass,
  Image,
  Inbox,
  Infinity,
  Info,
  Italic,
  Kanban,
  Key,
  KeyRound,
  Keyboard,
  Landmark,
  Languages,
  Laptop,
  Laugh,
  Layers,
  LayoutGrid,
  LayoutList,
  LayoutTemplate,
  Leaf,
  Lightbulb,
  LineChart,
  Link,
  Link2,
  List,
  ListChecks,
  ListOrdered,
  ListTodo,
  Lock,
  LockOpen,
  LogIn,
  LogOut,
  Luggage,
  Magnet,
  Mail,
  MailOpen,
  Map,
  MapPin,
  Maximize,
  Medal,
  Megaphone,
  Meh,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  MicOff,
  Microscope,
  Minimize,
  Minus,
  Monitor,
  MonitorPlay,
  Moon,
  Mountain,
  MountainSnow,
  Mouse,
  Move,
  MoveRight,
  Music,
  Navigation,
  Newspaper,
  Notebook,
  NotebookPen,
  Package,
  PaintBucket,
  Paintbrush,
  Palette,
  Paperclip,
  PartyPopper,
  Pause,
  PauseCircle,
  Pen,
  PenTool,
  Pencil,
  PencilRuler,
  Percent,
  PersonStanding,
  Phone,
  PhoneCall,
  PhoneIncoming,
  PhoneOutgoing,
  PieChart,
  PiggyBank,
  Pin,
  PinOff,
  Pipette,
  Pizza,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Play,
  PlayCircle,
  Plug,
  Plus,
  Power,
  Presentation,
  Printer,
  Puzzle,
  QrCode,
  Quote,
  Rabbit,
  Radio,
  Receipt,
  Recycle,
  Redo2,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Reply,
  Rewind,
  Rocket,
  RotateCcw,
  RotateCw,
  Rss,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  Save,
  Scale,
  Scissors,
  Scroll,
  Search,
  Send,
  Server,
  Settings,
  Shapes,
  Share,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sigma,
  SkipBack,
  SkipForward,
  Skull,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Snowflake,
  Soup,
  Sparkle,
  Sparkles,
  Speaker,
  Speech,
  Sprout,
  Star,
  StickyNote,
  StopCircle,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Table,
  Tablet,
  Tag,
  Tags,
  Target,
  Telescope,
  Tent,
  Terminal,
  TestTube,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  Timer,
  Trash2,
  TreeDeciduous,
  TreePine,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  Tv,
  Type,
  Umbrella,
  Underline,
  Undo2,
  Upload,
  Usb,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Utensils,
  UtensilsCrossed,
  Video,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Wallet,
  Wand2,
  Watch,
  Waves,
  Wifi,
  WifiOff,
  Wind,
  Wine,
  Wrench,
  X,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from "lucide-react";

/**
 * Thư viện icon lucide cho IconElement — import TƯỜNG MINH (tree-shake được),
 * KHÔNG import động cả bộ. `name` lưu trong JSON content là key kebab-case ở đây.
 * File này được sinh bằng script (đã validate tên với exports lucide-react) —
 * thêm icon: thêm key + import tương ứng, KHÔNG xóa key cũ (content đã lưu tham chiếu).
 */
export const SLIDE_ICONS: Record<string, LucideIcon> = {
  // Mũi tên & điều hướng
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "arrow-up-right": ArrowUpRight,
  "arrow-down-right": ArrowDownRight,
  "arrow-up-left": ArrowUpLeft,
  "arrow-down-left": ArrowDownLeft,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  "chevrons-right": ChevronsRight,
  "chevrons-left": ChevronsLeft,
  "chevrons-up": ChevronsUp,
  "chevrons-down": ChevronsDown,
  "move": Move,
  "move-right": MoveRight,
  "corner-down-right": CornerDownRight,
  "corner-up-right": CornerUpRight,
  "corner-down-left": CornerDownLeft,
  "corner-up-left": CornerUpLeft,
  "refresh-cw": RefreshCw,
  "refresh-ccw": RefreshCcw,
  "rotate-cw": RotateCw,
  "rotate-ccw": RotateCcw,
  "repeat": Repeat,
  "shuffle": Shuffle,
  "undo-2": Undo2,
  "redo-2": Redo2,
  "external-link": ExternalLink,
  "log-in": LogIn,
  "log-out": LogOut,
  "download": Download,
  "upload": Upload,
  "share-2": Share2,
  "send": Send,
  "navigation": Navigation,
  // Kinh doanh & tài chính
  "briefcase": Briefcase,
  "building": Building,
  "building-2": Building2,
  "landmark": Landmark,
  "banknote": Banknote,
  "coins": Coins,
  "credit-card": CreditCard,
  "wallet": Wallet,
  "piggy-bank": PiggyBank,
  "dollar-sign": DollarSign,
  "euro": Euro,
  "percent": Percent,
  "receipt": Receipt,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  "store": Store,
  "package": Package,
  "truck": Truck,
  "handshake": Handshake,
  "scale": Scale,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "bar-chart": BarChart3,
  "line-chart": LineChart,
  "pie-chart": PieChart,
  "activity": Activity,
  "target": Target,
  "award": Award,
  "trophy": Trophy,
  "medal": Medal,
  "crown": Crown,
  "gem": Gem,
  "badge-check": BadgeCheck,
  "gauge": Gauge,
  // Giao tiếp
  "mail": Mail,
  "mail-open": MailOpen,
  "inbox": Inbox,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "messages-square": MessagesSquare,
  "phone": Phone,
  "phone-call": PhoneCall,
  "phone-incoming": PhoneIncoming,
  "phone-outgoing": PhoneOutgoing,
  "voicemail": Voicemail,
  "at-sign": AtSign,
  "hash": Hash,
  "bell": Bell,
  "bell-ring": BellRing,
  "bell-off": BellOff,
  "megaphone": Megaphone,
  "radio": Radio,
  "rss": Rss,
  "share": Share,
  "reply": Reply,
  "quote": Quote,
  "languages": Languages,
  "speech": Speech,
  // Tệp & tài liệu
  "file": File,
  "file-text": FileText,
  "file-plus": FilePlus,
  "file-minus": FileMinus,
  "file-check": FileCheck,
  "file-x": FileX,
  "file-search": FileSearch,
  "file-code": FileCode,
  "file-image": FileImage,
  "file-video": FileVideo,
  "files": Files,
  "folder": Folder,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  "folder-minus": FolderMinus,
  "archive": Archive,
  "clipboard": Clipboard,
  "clipboard-list": ClipboardList,
  "clipboard-check": ClipboardCheck,
  "clipboard-copy": ClipboardCopy,
  "book": Book,
  "book-open": BookOpen,
  "book-marked": BookMarked,
  "notebook": Notebook,
  "notebook-pen": NotebookPen,
  "newspaper": Newspaper,
  "scroll": Scroll,
  "sticky-note": StickyNote,
  "bookmark": Bookmark,
  "paperclip": Paperclip,
  "printer": Printer,
  "save": Save,
  // Ảnh & media
  "image": Image,
  "camera": Camera,
  "video": Video,
  "film": Film,
  "clapperboard": Clapperboard,
  "play": Play,
  "pause": Pause,
  "play-circle": PlayCircle,
  "pause-circle": PauseCircle,
  "stop-circle": StopCircle,
  "skip-forward": SkipForward,
  "skip-back": SkipBack,
  "fast-forward": FastForward,
  "rewind": Rewind,
  "music": Music,
  "mic": Mic,
  "mic-off": MicOff,
  "volume": Volume,
  "volume-1": Volume1,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  "headphones": Headphones,
  "speaker": Speaker,
  "tv": Tv,
  "monitor-play": MonitorPlay,
  "disc": Disc,
  "aperture": Aperture,
  // Công nghệ
  "laptop": Laptop,
  "monitor": Monitor,
  "smartphone": Smartphone,
  "tablet": Tablet,
  "watch": Watch,
  "keyboard": Keyboard,
  "mouse": Mouse,
  "cpu": Cpu,
  "hard-drive": HardDrive,
  "database": Database,
  "server": Server,
  "cloud": Cloud,
  "cloud-upload": CloudUpload,
  "cloud-download": CloudDownload,
  "wifi": Wifi,
  "wifi-off": WifiOff,
  "bluetooth": Bluetooth,
  "battery": Battery,
  "battery-charging": BatteryCharging,
  "battery-full": BatteryFull,
  "battery-low": BatteryLow,
  "plug": Plug,
  "usb": Usb,
  "code": Code,
  "terminal": Terminal,
  "bug": Bug,
  "git-branch": GitBranch,
  "git-merge": GitMerge,
  "git-pull-request": GitPullRequest,
  "globe": Globe,
  "link": Link,
  "link-2": Link2,
  "qr-code": QrCode,
  "binary": Binary,
  "braces": Braces,
  "command": Command,
  "power": Power,
  "settings": Settings,
  "wrench": Wrench,
  "hammer": Hammer,
  "cog": Cog,
  "bot": Bot,
  // Con người & cảm xúc
  "user": User,
  "users": Users,
  "user-plus": UserPlus,
  "user-minus": UserMinus,
  "user-check": UserCheck,
  "user-x": UserX,
  "contact": Contact,
  "baby": Baby,
  "person-standing": PersonStanding,
  "accessibility": Accessibility,
  "heart-handshake": HeartHandshake,
  "smile": Smile,
  "frown": Frown,
  "meh": Meh,
  "laugh": Laugh,
  "angry": Angry,
  "thumbs-up": ThumbsUp,
  "thumbs-down": ThumbsDown,
  "hand": Hand,
  "footprints": Footprints,
  "eye": Eye,
  "eye-off": EyeOff,
  "brain": Brain,
  // Thiên nhiên & thời tiết
  "sun": Sun,
  "moon": Moon,
  "sunrise": Sunrise,
  "sunset": Sunset,
  "cloud-sun": CloudSun,
  "cloud-moon": CloudMoon,
  "cloud-rain": CloudRain,
  "cloud-snow": CloudSnow,
  "cloud-lightning": CloudLightning,
  "wind": Wind,
  "snowflake": Snowflake,
  "droplet": Droplet,
  "droplets": Droplets,
  "waves": Waves,
  "umbrella": Umbrella,
  "thermometer": Thermometer,
  "flame": Flame,
  "leaf": Leaf,
  "tree-pine": TreePine,
  "tree-deciduous": TreeDeciduous,
  "sprout": Sprout,
  "flower": Flower,
  "flower-2": Flower2,
  "bird": Bird,
  "fish": Fish,
  "cat": Cat,
  "dog": Dog,
  "rabbit": Rabbit,
  "mountain": Mountain,
  "mountain-snow": MountainSnow,
  // Ẩm thực & du lịch
  "coffee": Coffee,
  "cup-soda": CupSoda,
  "wine": Wine,
  "beer": Beer,
  "pizza": Pizza,
  "cookie": Cookie,
  "croissant": Croissant,
  "apple": Apple,
  "banana": Banana,
  "cherry": Cherry,
  "egg": Egg,
  "utensils": Utensils,
  "utensils-crossed": UtensilsCrossed,
  "chef-hat": ChefHat,
  "soup": Soup,
  "salad": Salad,
  "sandwich": Sandwich,
  "candy": Candy,
  "plane": Plane,
  "plane-takeoff": PlaneTakeoff,
  "plane-landing": PlaneLanding,
  "car": Car,
  "bus": Bus,
  "ship": Ship,
  "sailboat": Sailboat,
  "anchor": Anchor,
  "bike": Bike,
  "fuel": Fuel,
  "map": Map,
  "map-pin": MapPin,
  "compass": Compass,
  "luggage": Luggage,
  "tent": Tent,
  "hotel": Hotel,
  "ticket": Ticket,
  // Giáo dục & khoa học
  "graduation-cap": GraduationCap,
  "pencil": Pencil,
  "pen": Pen,
  "pen-tool": PenTool,
  "eraser": Eraser,
  "ruler": Ruler,
  "calculator": Calculator,
  "flask-conical": FlaskConical,
  "test-tube": TestTube,
  "microscope": Microscope,
  "telescope": Telescope,
  "atom": Atom,
  "dna": Dna,
  "magnet": Magnet,
  "sigma": Sigma,
  "lightbulb": Lightbulb,
  "glasses": Glasses,
  "backpack": Backpack,
  "presentation": Presentation,
  // Thiết kế & bố cục
  "palette": Palette,
  "paintbrush": Paintbrush,
  "paint-bucket": PaintBucket,
  "brush": Brush,
  "pipette": Pipette,
  "pencil-ruler": PencilRuler,
  "crop": Crop,
  "scissors": Scissors,
  "layout-grid": LayoutGrid,
  "layout-list": LayoutList,
  "layout-template": LayoutTemplate,
  "layers": Layers,
  "component": Component,
  "shapes": Shapes,
  "box": Box,
  "boxes": Boxes,
  "grid-3x3": Grid3x3,
  "table": Table,
  "kanban": Kanban,
  "align-left": AlignLeft,
  "align-center": AlignCenter,
  "align-right": AlignRight,
  "type": Type,
  "bold": Bold,
  "italic": Italic,
  "underline": Underline,
  "list": List,
  "list-ordered": ListOrdered,
  "list-checks": ListChecks,
  "list-todo": ListTodo,
  "wand-2": Wand2,
  "sparkle": Sparkle,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
  "maximize": Maximize,
  "minimize": Minimize,
  "expand": Expand,
  "focus": Focus,
  "sliders-horizontal": SlidersHorizontal,
  "filter": Filter,
  "frame": Frame,
  // Ký hiệu & UI
  "sparkles": Sparkles,
  "check": Check,
  "check-check": CheckCheck,
  "x": X,
  "plus": Plus,
  "minus": Minus,
  "equal": Equal,
  "divide": Divide,
  "circle-check": CircleCheck,
  "circle-x": CircleX,
  "circle-alert": CircleAlert,
  "circle-help": CircleHelp,
  "triangle-alert": TriangleAlert,
  "info": Info,
  "ban": Ban,
  "shield": Shield,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  "lock": Lock,
  "lock-open": LockOpen,
  "key": Key,
  "key-round": KeyRound,
  "fingerprint": Fingerprint,
  "star": Star,
  "heart": Heart,
  "flag": Flag,
  "pin": Pin,
  "pin-off": PinOff,
  "tag": Tag,
  "tags": Tags,
  "gift": Gift,
  "party-popper": PartyPopper,
  "rocket": Rocket,
  "zap": Zap,
  "zap-off": ZapOff,
  "timer": Timer,
  "clock": Clock,
  "calendar": Calendar,
  "calendar-days": CalendarDays,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  "hourglass": Hourglass,
  "alarm-clock": AlarmClock,
  "history": History,
  "infinity": Infinity,
  "puzzle": Puzzle,
  "dice-5": Dice5,
  "gamepad-2": Gamepad2,
  "ghost": Ghost,
  "skull": Skull,
  "search": Search,
  "home": Home,
  "menu": Menu,
  "trash-2": Trash2,
  "recycle": Recycle,
};

export type IconCategory = { id: string; label: string; icons: string[] };

/** Nhóm icon theo chủ đề — dùng cho Icon Picker (search/category). */
export const ICON_CATEGORIES: IconCategory[] = [
  {
    id: "arrows",
    label: "Mũi tên & điều hướng",
    icons: [
      "arrow-right", "arrow-left", "arrow-up", "arrow-down", "arrow-up-right", "arrow-down-right", "arrow-up-left", "arrow-down-left",
      "chevron-right", "chevron-left", "chevron-up", "chevron-down", "chevrons-right", "chevrons-left", "chevrons-up", "chevrons-down",
      "move", "move-right", "corner-down-right", "corner-up-right", "corner-down-left", "corner-up-left", "refresh-cw", "refresh-ccw",
      "rotate-cw", "rotate-ccw", "repeat", "shuffle", "undo-2", "redo-2", "external-link", "log-in",
      "log-out", "download", "upload", "share-2", "send", "navigation",
    ],
  },
  {
    id: "business",
    label: "Kinh doanh & tài chính",
    icons: [
      "briefcase", "building", "building-2", "landmark", "banknote", "coins", "credit-card", "wallet",
      "piggy-bank", "dollar-sign", "euro", "percent", "receipt", "shopping-cart", "shopping-bag", "store",
      "package", "truck", "handshake", "scale", "trending-up", "trending-down", "bar-chart", "line-chart",
      "pie-chart", "activity", "target", "award", "trophy", "medal", "crown", "gem",
      "badge-check", "gauge",
    ],
  },
  {
    id: "communication",
    label: "Giao tiếp",
    icons: [
      "mail", "mail-open", "inbox", "message-circle", "message-square", "messages-square", "phone", "phone-call",
      "phone-incoming", "phone-outgoing", "voicemail", "at-sign", "hash", "bell", "bell-ring", "bell-off",
      "megaphone", "radio", "rss", "share", "reply", "quote", "languages", "speech",
    ],
  },
  {
    id: "files",
    label: "Tệp & tài liệu",
    icons: [
      "file", "file-text", "file-plus", "file-minus", "file-check", "file-x", "file-search", "file-code",
      "file-image", "file-video", "files", "folder", "folder-open", "folder-plus", "folder-minus", "archive",
      "clipboard", "clipboard-list", "clipboard-check", "clipboard-copy", "book", "book-open", "book-marked", "notebook",
      "notebook-pen", "newspaper", "scroll", "sticky-note", "bookmark", "paperclip", "printer", "save",
    ],
  },
  {
    id: "media",
    label: "Ảnh & media",
    icons: [
      "image", "camera", "video", "film", "clapperboard", "play", "pause", "play-circle",
      "pause-circle", "stop-circle", "skip-forward", "skip-back", "fast-forward", "rewind", "music", "mic",
      "mic-off", "volume", "volume-1", "volume-2", "volume-x", "headphones", "speaker", "tv",
      "monitor-play", "disc", "aperture",
    ],
  },
  {
    id: "technology",
    label: "Công nghệ",
    icons: [
      "laptop", "monitor", "smartphone", "tablet", "watch", "keyboard", "mouse", "cpu",
      "hard-drive", "database", "server", "cloud", "cloud-upload", "cloud-download", "wifi", "wifi-off",
      "bluetooth", "battery", "battery-charging", "battery-full", "battery-low", "plug", "usb", "code",
      "terminal", "bug", "git-branch", "git-merge", "git-pull-request", "globe", "link", "link-2",
      "qr-code", "binary", "braces", "command", "power", "settings", "wrench", "hammer",
      "cog", "bot",
    ],
  },
  {
    id: "people",
    label: "Con người & cảm xúc",
    icons: [
      "user", "users", "user-plus", "user-minus", "user-check", "user-x", "contact", "baby",
      "person-standing", "accessibility", "heart-handshake", "smile", "frown", "meh", "laugh", "angry",
      "thumbs-up", "thumbs-down", "hand", "footprints", "eye", "eye-off", "brain",
    ],
  },
  {
    id: "nature",
    label: "Thiên nhiên & thời tiết",
    icons: [
      "sun", "moon", "sunrise", "sunset", "cloud-sun", "cloud-moon", "cloud-rain", "cloud-snow",
      "cloud-lightning", "wind", "snowflake", "droplet", "droplets", "waves", "umbrella", "thermometer",
      "flame", "leaf", "tree-pine", "tree-deciduous", "sprout", "flower", "flower-2", "bird",
      "fish", "cat", "dog", "rabbit", "mountain", "mountain-snow",
    ],
  },
  {
    id: "food_travel",
    label: "Ẩm thực & du lịch",
    icons: [
      "coffee", "cup-soda", "wine", "beer", "pizza", "cookie", "croissant", "apple",
      "banana", "cherry", "egg", "utensils", "utensils-crossed", "chef-hat", "soup", "salad",
      "sandwich", "candy", "plane", "plane-takeoff", "plane-landing", "car", "bus", "ship",
      "sailboat", "anchor", "bike", "fuel", "map", "map-pin", "compass", "luggage",
      "tent", "hotel", "ticket",
    ],
  },
  {
    id: "education",
    label: "Giáo dục & khoa học",
    icons: [
      "graduation-cap", "pencil", "pen", "pen-tool", "eraser", "ruler", "calculator", "flask-conical",
      "test-tube", "microscope", "telescope", "atom", "dna", "magnet", "sigma", "lightbulb",
      "glasses", "backpack", "presentation",
    ],
  },
  {
    id: "design",
    label: "Thiết kế & bố cục",
    icons: [
      "palette", "paintbrush", "paint-bucket", "brush", "pipette", "pencil-ruler", "crop", "scissors",
      "layout-grid", "layout-list", "layout-template", "layers", "component", "shapes", "box", "boxes",
      "grid-3x3", "table", "kanban", "align-left", "align-center", "align-right", "type", "bold",
      "italic", "underline", "list", "list-ordered", "list-checks", "list-todo", "wand-2", "sparkle",
      "zoom-in", "zoom-out", "maximize", "minimize", "expand", "focus", "sliders-horizontal", "filter",
      "frame",
    ],
  },
  {
    id: "symbols",
    label: "Ký hiệu & UI",
    icons: [
      "sparkles", "check", "check-check", "x", "plus", "minus", "equal", "divide",
      "circle-check", "circle-x", "circle-alert", "circle-help", "triangle-alert", "info", "ban", "shield",
      "shield-check", "shield-alert", "lock", "lock-open", "key", "key-round", "fingerprint", "star",
      "heart", "flag", "pin", "pin-off", "tag", "tags", "gift", "party-popper",
      "rocket", "zap", "zap-off", "timer", "clock", "calendar", "calendar-days", "calendar-check",
      "calendar-clock", "hourglass", "alarm-clock", "history", "infinity", "puzzle", "dice-5", "gamepad-2",
      "ghost", "skull", "search", "home", "menu", "trash-2", "recycle",
    ],
  },
];

export const DEFAULT_ICON_NAME = "sparkles";
